#!/usr/bin/env python3
"""Push the shell's theme to the apps outside it.

Reads the resolved theme as JSON on stdin (services/ThemeSync.qml sends it:
id, variant, shape, palette, roles), writes one small file per app into
~/.local/state/rice/theme/ (stowed configs include those, never edited), and
reloads what is running:

    hyprland   rounding + borders      live (hyprctl)
    ghostty    colours + ANSI palette  live (SIGUSR2)
    tmux       status line + borders   live (source-file)
    nvim       mini.base16 palette     live (running instances via their sockets)
    gtk        prefer-dark / -light    live (gsettings)
    btop       ~/.config/btop/themes/rice.theme   next start
    zathura    colours include          next start
    sddm       theme.conf.user (needs the one-time setup in sddm/README.md)
    firefox    textfox config.css in the profile's chrome/   next start

    theme-apply.py [--dry-run] [--only app,app] < theme.json
"""
import json, os, subprocess, sys, glob, argparse
from pathlib import Path

HOME = Path.home()
OUT = HOME / ".local/state/rice/theme"
SDDM_USER = Path("/usr/share/sddm/themes/rice/theme.conf.user")


def hexa(c):
    """'#rrggbb' or '#aarrggbb' (Qt) → 'rrggbb'."""
    c = c.lstrip("#")
    return c[-6:].lower()


def ansi(t):
    """16 ANSI colours. Dark: 0 = dark grey, 7 = text. Light: inverted ends,
    so TUIs that assume a dark background still read."""
    p, r = t["palette"], t["roles"]
    hues = ["red", "green", "yellow", "blue", "purple", "aqua"]
    if t.get("variant") == "light":
        lo, hi, lo2, hi2 = r["text"], p["bg3"], r["subtext"], p["bg0"]
    else:
        lo, hi, lo2, hi2 = p["bg3"], r["text"], r["muted"], r["textBright"]
    return [lo] + [p[h] for h in hues] + [hi] + [lo2] + [p[h + "Bright"] for h in hues] + [hi2]


# --- renderers: (filename, text) ------------------------------------------

def hyprland(t):
    r = t["roles"]
    rounding = 10 if t["shape"] == "round" else 0
    return "hyprland.conf", f"""# Generated by theme-apply.py from {t['id']} — don't edit.
general {{
    col.active_border = rgba({hexa(r['outline'])}ff)
    col.inactive_border = rgba({hexa(r['surface2'])}aa)
}}
decoration {{
    rounding = {rounding}
}}
"""


def ghostty(t):
    r = t["roles"]
    lines = [f"# Generated by theme-apply.py from {t['id']} — don't edit.",
             f"background = #{hexa(r['background'])}",
             f"foreground = #{hexa(r['text'])}",
             f"cursor-color = #{hexa(r['text'])}",
             f"selection-background = #{hexa(r['surface2'])}",
             f"selection-foreground = #{hexa(r['textBright'])}"]
    lines += [f"palette = {i}=#{hexa(c)}" for i, c in enumerate(ansi(t))]
    return "ghostty", "\n".join(lines) + "\n"


def ghostty_gtk(t):
    """GTK CSS for ghostty's own UI: toasts (clipboard copy), the resize-size
    overlay and the link-hover popup, drawn like the shell's panels."""
    r = t["roles"]
    c = lambda k: "#" + hexa(r[k])
    rad = "10px" if t["shape"] == "round" else "0"
    font = t.get("font") or "DepartureMono Nerd Font Mono"
    return "ghostty-gtk.css", f"""/* Generated by theme-apply.py from {t['id']} — don't edit. */
toast {{
  background-color: {c('background')};
  color: {c('text')};
  border: 2px solid {c('outline')};
  border-radius: {rad};
  box-shadow: none;
  font-family: "{font}";
  padding: 4px 8px;
}}
toast label {{ color: {c('textBright')}; }}
toast button {{
  background: none;
  color: {c('accent')};
  border-radius: {rad};
  box-shadow: none;
}}
toast button:hover {{ background-color: {c('surface1')}; }}

.size-overlay, .url-overlay {{
  background-color: {c('background')};
  color: {c('text')};
  border: 2px solid {c('outline')};
  border-radius: {rad};
  font-family: "{font}";
  box-shadow: none;
}}
"""


def tmux(t):
    r = t["roles"]
    c = {k: "#" + hexa(v) for k, v in r.items()}
    rnd = t["shape"] == "round"
    # Round: soft caps around blocks; square: flat retro blocks.
    l, rr = ("", "") if rnd else ("", "")
    return "tmux.conf", f"""# Generated by theme-apply.py from {t['id']} — don't edit.
# Colours as user options: tmux.conf's status-right reads them, so it is
# never rewritten here (continuum's autosave hook lives in it).
set -g @rice_bg "{c['background']}"
set -g @rice_bar "{c['surface1']}"
set -g @rice_block "{c['surface2']}"
set -g @rice_text "{c['text']}"
set -g @rice_bright "{c['textBright']}"
set -g @rice_sub "{c['subtext']}"
set -g @rice_accent "{c['accent']}"
set -g @rice_rev "{c['textReverse']}"
set -g @rice_capl "{l}"
set -g @rice_capr "{rr}"

set -g status-style "fg={c['text']},bg={c['surface1']}"
set -g status-left "#[fg={c['accent']},bg={c['surface1']}]{l}#[fg={c['textReverse']},bg={c['accent']},bold] #S #[fg={c['accent']},bg={c['surface1']},nobold]{rr} "
set -g window-status-format "#[fg={c['subtext']}] #I #W "
set -g window-status-current-format "#[fg={c['surface2']},bg={c['surface1']}]{l}#[fg={c['accent']},bg={c['surface2']},bold]#I #[fg={c['textBright']}]#W#[fg={c['surface2']},bg={c['surface1']},nobold]{rr}"
set -g window-status-separator ""
set -g pane-border-style "fg={c['surface2']}"
set -g pane-active-border-style "fg={c['accent']}"
set -g message-style "fg={c['textBright']},bg={c['surface2']}"
set -g message-command-style "fg={c['textBright']},bg={c['surface2']}"
set -g mode-style "fg={c['textReverse']},bg={c['accent']}"
set -g clock-mode-colour "{c['accent']}"
set -g display-panes-active-colour "{c['accent']}"
set -g display-panes-colour "{c['subtext']}"
"""


def nvim(t):
    p, r = t["palette"], t["roles"]
    # base16 slots, from the theme's own roles so nvim matches the shell.
    b = [r["background"], p["bg0"] if t.get("variant") != "light" else p["bg2"], r["surface2"], r["muted"],
         r["subtext"], r["text"], r["textBright"], p["fg1"],
         p["red"], p["orange"], p["yellow"], p["green"], p["aqua"], p["blue"], p["purple"], p["orangeDim"]]
    pal = ",\n".join(f'  base{i:02X} = "#{hexa(c)}"' for i, c in enumerate(b))
    return "nvim.lua", f"""-- Generated by theme-apply.py from {t['id']} — don't edit.
return {{
 id = "{t['id']}",
 background = "{'light' if t.get('variant') == 'light' else 'dark'}",
 palette = {{
{pal}
 }},
}}
"""


def btop(t):
    p, r = t["palette"], t["roles"]
    h = lambda k: "#" + hexa(r[k] if k in r else p[k])
    keys = {
        "main_bg": h("background"), "main_fg": h("text"), "title": h("textBright"),
        "hi_fg": h("accent"), "selected_bg": h("surface2"), "selected_fg": h("textBright"),
        "inactive_fg": h("muted"), "graph_text": h("subtext"), "meter_bg": h("surface2"),
        "proc_misc": h("aqua"), "cpu_box": h("blue"), "mem_box": h("aqua"), "net_box": h("purple"),
        "proc_box": h("accent"), "div_line": h("surface2"),
        "temp_start": h("green"), "temp_mid": h("yellow"), "temp_end": h("red"),
        "cpu_start": h("blue"), "cpu_mid": h("aqua"), "cpu_end": h("green"),
        "free_start": h("green"), "free_mid": h("aqua"), "free_end": h("blue"),
        "cached_start": h("yellow"), "cached_mid": h("orange"), "cached_end": h("red"),
        "available_start": h("aqua"), "available_mid": h("blue"), "available_end": h("purple"),
        "used_start": h("purple"), "used_mid": h("orange"), "used_end": h("red"),
        "download_start": h("blue"), "download_mid": h("aqua"), "download_end": h("green"),
        "upload_start": h("purple"), "upload_mid": h("orange"), "upload_end": h("red"),
        "process_start": h("green"), "process_mid": h("yellow"), "process_end": h("red"),
    }
    return "btop.theme", f"# Generated by theme-apply.py from {t['id']} — don't edit.\n" + \
        "\n".join(f'theme[{k}]="{v}"' for k, v in keys.items()) + "\n"


def zathura(t):
    r, p = t["roles"], t["palette"]
    c = lambda k: "#" + hexa(r[k] if k in r else p[k])
    light = t.get("variant") == "light"
    return "zathurarc", f"""# Generated by theme-apply.py from {t['id']} — don't edit.
set default-bg                  "{c('background')}"
set default-fg                  "{c('text')}"
set statusbar-bg                "{c('surface1')}"
set statusbar-fg                "{c('text')}"
set inputbar-bg                 "{c('surface0')}"
set inputbar-fg                 "{c('textBright')}"
set notification-bg             "{c('surface1')}"
set notification-fg             "{c('text')}"
set notification-error-bg       "{c('surface1')}"
set notification-error-fg       "{c('error')}"
set notification-warning-bg     "{c('surface1')}"
set notification-warning-fg     "{c('warning')}"
set completion-bg               "{c('surface0')}"
set completion-fg               "{c('text')}"
set completion-highlight-bg     "{c('accent')}"
set completion-highlight-fg     "{c('textReverse')}"
set index-bg                    "{c('background')}"
set index-fg                    "{c('text')}"
set index-active-bg             "{c('accent')}"
set index-active-fg             "{c('textReverse')}"
set highlight-color             "{c('accent')}"
set highlight-active-color      "{c('orange')}"
set recolor-lightcolor          "{c('background')}"
set recolor-darkcolor           "{c('text')}"
set recolor                     "{'false' if light else 'true'}"
"""


def sddm(t):
    r, p = t["roles"], t["palette"]
    c = lambda k: "#" + hexa(r[k] if k in r else p[k])
    return "sddm.conf", f"""# Generated by theme-apply.py from {t['id']} — don't edit.
# Copied to {SDDM_USER} when that file is writable (sddm/README.md).
[General]
background=background.jpg
bg0={c('surface0')}
bg1={c('background')}
bg2={c('surface1')}
bg3={c('surface2')}
fg0={c('text')}
fg1={c('textBright')}
grey={c('subtext')}
greyDim={c('muted')}
red={c('error')}
orange={c('warning')}
yellow={c('accent')}
purple={c('catMedia')}
blue={c('info')}
outline={c('outline')}
shape={t['shape']}
"""


def firefox(t):
    r = t["roles"]
    c = lambda k: "#" + hexa(r[k])
    rounding = "8px" if t["shape"] == "round" else "0px"
    return "firefox.css", f"""/* Generated by theme-apply.py from {t['id']} — don't edit.
   textfox's config.css (copied into the profile's chrome/); read at startup. */
:root {{
  --tf-font-family: "{t.get('font') or 'DepartureMono Nerd Font Mono'}", monospace;
  --tf-bg: {c('background')};
  --tf-border: {c('surface2')};
  --tf-accent: {c('accent')};
  --tf-rounding: {rounding};
  --toolbar-bgcolor: {c('background')};
  --toolbar-color: {c('text')};
  --toolbar-field-background-color: {c('surface0')};
  --toolbar-field-color: {c('textBright')};
  --toolbar-field-focus-background-color: {c('surface0')};
  --lwt-accent-color: {c('background')};
  --lwt-text-color: {c('text')};
  --arrowpanel-background: {c('background')};
  --arrowpanel-color: {c('text')};
  --tab-selected-bgcolor: {c('surface1')};
  --tab-selected-textcolor: {c('textBright')};
}}
"""


RENDERERS = {"hyprland": hyprland, "ghostty-gtk": ghostty_gtk, "ghostty": ghostty, "tmux": tmux, "nvim": nvim,
             "btop": btop, "zathura": zathura, "sddm": sddm, "firefox": firefox}


# --- reloaders ------------------------------------------------------------

def run(cmd, **kw):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=10, **kw)
    except (OSError, subprocess.TimeoutExpired):
        return None


def reload(app, path, t):
    if app == "hyprland":
        r = t["roles"]
        rounding = 10 if t["shape"] == "round" else 0
        run(["hyprctl", "--batch",
             f"keyword decoration:rounding {rounding} ; "
             f"keyword general:col.active_border rgba({hexa(r['outline'])}ff) ; "
             f"keyword general:col.inactive_border rgba({hexa(r['surface2'])}aa)"])
    elif app == "ghostty":
        run(["pkill", "-USR2", "-x", "ghostty"])
    elif app == "tmux":
        r = run(["tmux", "has-session"])
        if r and r.returncode == 0:
            run(["tmux", "source-file", str(path)])
    elif app == "nvim":
        rt = os.environ.get("XDG_RUNTIME_DIR", f"/run/user/{os.getuid()}")
        for sock in glob.glob(f"{rt}/nvim.*.0"):
            run(["nvim", "--server", sock, "--remote-send", "<Cmd>lua if RiceTheme then RiceTheme() end<CR>"])
    elif app == "btop":
        dst = HOME / ".config/btop/themes/rice.theme"
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(path.read_text())
    elif app == "firefox":
        profiles = glob.glob(str(HOME / ".mozilla/firefox/*.default-release/chrome"))
        for chrome in profiles:
            Path(chrome, "config.css").write_text(path.read_text())
        return "next Firefox start" if profiles else "no textfox profile"
    elif app == "sddm":
        if os.access(SDDM_USER, os.W_OK):
            SDDM_USER.write_text(path.read_text())
            return "copied to " + str(SDDM_USER)
        return "not copied: run the one-time setup in sddm/README.md"


def gtk(t):
    scheme = "prefer-light" if t.get("variant") == "light" else "prefer-dark"
    run(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", scheme])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only", default="")
    a = ap.parse_args()
    t = json.load(sys.stdin)
    only = set(filter(None, a.only.split(",")))
    OUT.mkdir(parents=True, exist_ok=True)
    report = []
    for app, fn in RENDERERS.items():
        if only and app not in only:
            continue
        name, text = fn(t)
        path = OUT / name
        if a.dry_run:
            report.append(f"{app}: would write {path}")
            continue
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(text)
        tmp.replace(path)
        note = reload(app, path, t)
        report.append(f"{app}: {path.name}" + (f" ({note})" if note else ""))
    if not only or "gtk" in only:
        if not a.dry_run:
            gtk(t)
        report.append("gtk: " + ("prefer-light" if t.get("variant") == "light" else "prefer-dark"))
    print(f"{t['id']} ({t['shape']}): " + "; ".join(report))


if __name__ == "__main__":
    main()
