color_theme = "rice"
theme_background = False
truecolor = True
force_tty = False
vim_keys = True
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
cpu_graph_upper = "Auto"
cpu_graph_lower = "Auto"
show_uptime = True
check_temp = True
cpu_sensor = "Auto"
show_coretemp = True
temp_scale = "celsius"
base_10_sizes = False
show_battery = True
selected_battery = "Auto"
log_level = "WARNING"
